### ISSUE TITLE
Error: undefined method `plist_startup' for #<Formula reindexer (stable) /opt/homebrew/Library/Taps/restream/homebrew-reindexer/reindexer.rb>

### ISSUE THREAD

**Issue by szonov** [Restream/homebrew-reindexer#5]
I've got this error during start reindexer service on macos
```
service up reindexer
Error: undefined method `plist_startup' for #<Formula reindexer (stable) /opt/homebrew/Library/Taps/restream/homebrew-reindexer/reindexer.rb>
Did you mean?  plist_name
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:71:in `service_startup?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:280:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:122:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:139:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

Same problem also exists for other services and proposed following:
```ruby
  service do
    name macos: "#{plist_name}"
  end
```

I've put it to `/opt/homebrew/Library/Taps/restream/homebrew-reindexer/reindexer.rb` before install section and problem disappears.

Can you fix it also in repo?

**Comment by MadSchemas** [comment]
Thank you for the report. Added this fix in repo https://github.com/Restream/homebrew-reindexer/commit/2292bc944cf5ac020157dfc4ac296d4010073a29
